### PR TITLE
PackageJSON Namespacing

### PR DESCRIPTION
**Pull request by chrislloyd**
Currently SKPM overrides `package.json` for things other than their intended use. This makes it extremely difficult to integrate into existing projects. I currently have a UI library that I'd like to build a Sketch plugin for, however I'm unable to without either creating a second (useless) package or modifying SKPM. Hence why I'm here!

My proposal is for SKPM to take non-standard fields and namespace them in a "skpm" property. For instance, previously:

```json
{
  "name": "foo",
  "main": "foo.sketchplugin",
  "manifest": "./src/manifest.json"
}
```

would become

```json
{
  "name": "foo",
  "skpm": {
    "output": "foo.sketchplugin",
    "manifest": "./src/manifest.json"
  }
}
```

This would be a _breaking change_. I'd be happy to provide a backwards compatible version, but it might be easier and safer to just cut a new major version.

This commit is intentionally very rough – happy to polish, but I wanted the maintainer's input first. Happy to iterate with feedback.

### CODE REVIEW

**Comment by mathieudutour** [comment]
Yeah, I’ve been meaning to do this. 

A backward compatibility would be awesome, at least for 1 major version

**Comment by marionebl** [comment]
@mathieudutour To clarify: Backwards compatibility is required before this PR can land, right?
@chrislloyd: Are you interested in implementing this in a backwards compatible manner? I'd pick up the ball if required.

**Comment by mathieudutour** [comment]
yes indeed. I mean I can merge it but I won't cut a release quite yet if there is no backward comp. So I'd rather keep this open and build the backward comp here

**Comment by chrislloyd** [comment]
Gimmie a sec — I have some time now to work on this :)

**Comment by mathieudutour** [comment]
hi @chrislloyd, any idea when you will be able to finish this? No rush, it's just to know if I should publish a new version now with the #47 fix or wait for this

**Comment by chrislloyd** [comment]
Hey I'm really sorry, I've been swamped with other stuff recently. You should definitely move on and consider other patches.

**Comment by mathieudutour** [comment]
I finished the PR, really wanted to get it in. Thanks for the PR!

**Pull request merged**
